#ifndef PUS_SERVICES_H
#define PUS_SERVICES_H

/* ---- Service identifiers ---- */
#define PUS_SERVICE_REQUEST_VERIFICATION  1u
#define PUS_SERVICE_HOUSEKEEPING          3u
#define PUS_SERVICE_EVENT_REPORTING       5u
#define PUS_SERVICE_TEST                 17u
#define PUS_SERVICE_PARAMETER_MANAGEMENT 20u

/* ---- Service 1: request verification subtypes ---- */
#define PUS_SUBTYPE_VERIFICATION_ACCEPTANCE_SUCCESS  1u
#define PUS_SUBTYPE_VERIFICATION_ACCEPTANCE_FAILURE  2u
#define PUS_SUBTYPE_VERIFICATION_START_SUCCESS       3u
#define PUS_SUBTYPE_VERIFICATION_START_FAILURE       4u
#define PUS_SUBTYPE_VERIFICATION_PROGRESS_SUCCESS    5u
#define PUS_SUBTYPE_VERIFICATION_PROGRESS_FAILURE    6u
#define PUS_SUBTYPE_VERIFICATION_COMPLETION_SUCCESS  7u
#define PUS_SUBTYPE_VERIFICATION_COMPLETION_FAILURE  8u
#define PUS_SUBTYPE_VERIFICATION_ROUTING_FAILURE    10u

/* ---- Service 3: housekeeping subtypes ---- */
#define PUS_SUBTYPE_HOUSEKEEPING_PARAMETER_REPORT  25u
#define PUS_SUBTYPE_HOUSEKEEPING_DIAGNOSTIC_REPORT 26u

/* ---- Service 5: event reporting subtypes ---- */
#define PUS_SUBTYPE_EVENT_INFO            1u
#define PUS_SUBTYPE_EVENT_LOW_SEVERITY    2u
#define PUS_SUBTYPE_EVENT_MEDIUM_SEVERITY 3u
#define PUS_SUBTYPE_EVENT_HIGH_SEVERITY   4u

/* ---- Service 17: test subtypes ---- */
#define PUS_SUBTYPE_TEST_ARE_YOU_ALIVE              1u
#define PUS_SUBTYPE_TEST_ARE_YOU_ALIVE_REPORT       2u
#define PUS_SUBTYPE_TEST_ON_BOARD_CONNECTION        3u
#define PUS_SUBTYPE_TEST_ON_BOARD_CONNECTION_REPORT 4u

/* ---- Service 20: parameter management subtypes ---- */
#define PUS_SUBTYPE_PARAMETER_REPORT_VALUES 1u
#define PUS_SUBTYPE_PARAMETER_VALUE_REPORT  2u
#define PUS_SUBTYPE_PARAMETER_SET_VALUES    3u

#endif /* PUS_SERVICES_H */
